(() => {
'use strict';
const products = window.HERBAL_PRODUCTS;
const byId = new Map(products.map(p => [p.id,p]));
const $ = s => document.querySelector(s);
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const price = p => Number.isFinite(p.price) ? money(p.price) : 'Harga belum tersedia';
const platformNames = {shopee:'Shopee',tiktok:'TikTok Shop',lynk:'Lynk.id'};
function links(p){return Object.entries(p.links||{}).filter(([k,v])=>{try{return platformNames[k] && new URL(v).protocol==='https:';}catch{return false;}}).map(([k,v])=>`<a class="button" href="${escape(v)}" target="_blank" rel="noopener noreferrer">Beli di ${platformNames[k]} ↗</a>`).join('');}
let category='all', query='', order='default', cart={};
try { const saved=JSON.parse(localStorage.getItem('herbal-cart-v1')||'{}'); if(saved && typeof saved==='object' && !Array.isArray(saved)){for(const [id,n] of Object.entries(saved)){if(byId.has(id) && Number.isInteger(n) && n>0) cart[id]=Math.min(99,n);}} } catch {}
function save(){try{localStorage.setItem('herbal-cart-v1',JSON.stringify(cart));}catch{} updateCount();}
function updateCount(){$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);}
let timer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
function add(id){if(!byId.has(id))return;cart[id]=Math.min(99,(cart[id]||0)+1);save();toast('Produk ditambahkan ke keranjang');}
function render(){let shown=products.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.brand} ${p.size}`.toLocaleLowerCase('id').includes(query));if(order!=='default')shown.sort((a,b)=>order==='az'?a.name.localeCompare(b.name,'id'):b.name.localeCompare(a.name,'id'));$('#result-count').textContent=`${shown.length} produk ditemukan`;$('#empty').hidden=shown.length>0;$('#product-grid').innerHTML=shown.map(p=>`<article class="product-card"><div class="product-photo"><span class="category-label">${escape(p.category)}</span><button data-detail="${p.id}" aria-label="Lihat detail ${escape(p.name)} ${escape(p.size)}"><img src="${p.image}" alt="${escape(p.name)} ${escape(p.size)}" loading="lazy" width="400" height="420"></button></div><div class="product-meta">${escape(p.brand)} · ${escape(p.size)}</div><h3><button data-detail="${p.id}">${escape(p.name)}</button></h3><p class="product-description">${escape(p.description)}</p><div class="card-bottom"><span class="price">${escape(price(p))}</span><button class="add" data-add="${p.id}" aria-label="Tambah ${escape(p.name)} ${escape(p.size)} ke keranjang">+</button></div></article>`).join('');}
function detail(id){const p=byId.get(id);if(!p)return;const buy=links(p);$('#detail-content').innerHTML=`<div class="detail-layout"><img class="detail-image" src="${p.image}" alt="${escape(p.name)} ${escape(p.size)}"><div><span class="eyebrow">${escape(p.category)}</span><h2 id="detail-name">${escape(p.name)}</h2><p>${escape(p.brand)} · ${escape(p.size)}</p><p>${escape(p.description)}</p><strong>${escape(price(p))}</strong><div class="detail-actions"><button class="button primary" data-add="${p.id}">Tambahkan ke keranjang +</button>${buy||'<p>Link pembelian produk ini segera tersedia.</p>'}</div><p class="small">Periksa detail, petunjuk penggunaan, dan informasi pada kemasan sebelum membeli.</p></div></div>`;$('#product-dialog').showModal();}
function renderCart(){const entries=Object.entries(cart);$('#cart-items').innerHTML=entries.length?entries.map(([id,n])=>{const p=byId.get(id);return `<article class="cart-row"><img src="${p.image}" alt="${escape(p.name)}"><div class="cart-info"><h3>${escape(p.name)} · ${escape(p.size)}</h3><p class="small muted">${escape(price(p))}</p><div class="quantity"><button data-change="${id}" data-delta="-1" aria-label="Kurangi ${escape(p.name)}">−</button><span aria-label="Jumlah">${n}</span><button data-change="${id}" data-delta="1" aria-label="Tambah jumlah ${escape(p.name)}" ${n>=99?'disabled':''}>+</button><button class="remove" data-remove="${id}" aria-label="Hapus ${escape(p.name)}">Hapus</button></div><div class="cart-links">${links(p)||'<span class="muted small">Link pembelian segera tersedia.</span>'}</div></div></article>`;}).join(''):'<div class="empty"><h3>Keranjang masih kosong.</h3><p>Pilih produk di katalog untuk mulai membuat daftar.</p></div>';$('#copy-cart').disabled=!entries.length;}
document.addEventListener('click',e=>{const addButton=e.target.closest('[data-add]');if(addButton)add(addButton.dataset.add);const detailButton=e.target.closest('[data-detail]');if(detailButton)detail(detailButton.dataset.detail);const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();const change=e.target.closest('[data-change]');if(change){const id=change.dataset.change;if(cart[id]){cart[id]=Math.min(99,cart[id]+Number(change.dataset.delta));if(cart[id]<=0)delete cart[id];save();renderCart();}}const remove=e.target.closest('[data-remove]');if(remove){delete cart[remove.dataset.remove];save();renderCart();}});
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(btn=>{const active=btn===b;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',active);});render();});
$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLocaleLowerCase('id');render();});
$('#sort').addEventListener('change',e=>{order=e.target.value;render();});
$('#reset').addEventListener('click',()=>{$('#search').value='';query='';$('#filters button').click();});
$('#open-cart').addEventListener('click',()=>{renderCart();$('#cart-dialog').showModal();});
$('#copy-cart').addEventListener('click',async()=>{const text='Daftar pilihan produk:\n'+Object.entries(cart).map(([id,n])=>`${n} × ${byId.get(id).name} ${byId.get(id).size}`).join('\n')+'\n\nMohon konfirmasi harga, stok, dan ongkir.';try{await navigator.clipboard.writeText(text);toast('Daftar pilihan berhasil disalin');}catch{const area=document.createElement('textarea');area.value=text;area.style.cssText='position:fixed;opacity:0';$('#cart-dialog').append(area);area.select();let ok=false;try{ok=document.execCommand('copy');}catch{}area.remove();toast(ok?'Daftar pilihan berhasil disalin':'Belum bisa menyalin. Coba gunakan browser lain.');}});
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('#year').textContent=new Date().getFullYear();updateCount();render();
})();
